# documentation:
# slogan: Minecraft Server that will automatically download selected version at startup.
# tags: minecraft frps
# logo: 
# port: 25565, 7000

services:
  frps:
    image: 'ghcr.io/fatedier/frps:v0.64.0'
    restart: unless-stopped
    ports:
      - 7000:7000
    command:
      - '-c'
      - /frps.toml
    networks:
      - minecraft_network
    volumes:
      -
        type: bind
        source: ./frps.toml
        target: /frps.toml
        content: "bindPort = 7000\nauth.token = \"\""


  infrared:
    image: 'ghcr.io/haveachin/infrared:latest'
    restart: unless-stopped
    ports:
      - '25565:25565'
    networks:
      - minecraft_network
    depends_on:
      - frps
    volumes:
      -
        type: bind
        source: ./proxies/proxy1.yml
        target: /proxies/proxy1.yml
        content: "domains:\n  - \"example.com\"\naddresses:\n  - frps:25565"
      -
        type: bind
        source: ./infrared.yml
        target: /infrared.yml
        content: "bind: 0.0.0.0:25565\nkeepAliveTimeout: 30s"
    command:
      - '-c'
      - /infrared.yml
      - '-p'
      - /proxies

networks:
  minecraft_network:
    driver: bridge

