# documentation:
# slogan: Minecraft Server that will automatically download selected version at startup.
# tags: minecraft frps
# logo: 
# port: 25565, 7000

services:
  minecraft_frps:
    image: ghcr.io/fatedier/frps:v0.62.1
    container_name: minecraft_frps
    restart: unless-stopped
    ports:
      - 7000:7000
      - 25565:25565
    volumes:
      - ./frps.toml:/frps.toml
    command:
      - '-c'
      - /frps.toml

